#!/bin/bash

sudo apt-get upgrade -y
sudo apt-get update -y
sudo apt-get install -y gedit
sudo apt-get install -y git
sudo apt-get install -y s3cmd
sudo apt-get install -y zip
sudo apt-get install -y awscli
sudo apt-get install -y nodejs
sudo apt-get install npm


