#!/bin/bash

sudo apt-get upgrade -y
sudo apt-get update -y
sudo apt-get install -y gedit
sudo apt-get install -y git
sudo apt-get install -y jq
sudo apt-get install -y awscli
sudo apt-get install -y python-pip
sudo pip install --upgrade pip
sudo pip install --upgrade awscli
sudo apt-get install -y nodejs
sudo apt-get install -y npm
sudo reboot



