#!/bin/bash

echo "Starting build `date` in `pwd`"
cd js
npm install async gm
cd -

aws cloudformation package \
   --template-file ./CreateThumbnail.yaml \
   --output-template-file /tmp/CreateThumbnail-SAM.yaml \
   --s3-bucket $1 \
   --profile admin

aws cloudformation deploy \
  --template-file /tmp/CreateThumbnail-SAM.yaml \
  --stack-name CreateThumbnail \
  --capabilities CAPABILITY_IAM \
  --profile admin


