#!/bin/bash

cd js
npm install async gm
cd -
aws s3 mb s3://lambda-dev-tutorials \
   --profile admin

aws cloudformation package \
   --template-file ./CreateThumbnail.yaml \
   --output-template-file /tmp/CreateThumbnail-SAM.yaml \
   --s3-bucket lambda-dev-tutorials \
   --profile admin

