AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
    BuildArtifactsBucket:
        Type: AWS::S3::Bucket

    CodeBuildServiceRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Action: 
                      - 'sts:AssumeRole'
                    Effect: Allow
                    Principal:
                      Service:
                        - codebuild.amazonaws.com
            Path: /
            Policies:
                - PolicyName: CodeBuildAccess
                  PolicyDocument:
                    Version: '2012-10-17'
                    Statement:
                      - Effect: Allow
                        Resource:
                          - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/CreateThumbnail_build'
                          - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/CreateThumbnail_build:*'
                        Action:
                          - 'logs:CreateLogGroup'
                          - 'logs:CreateLogStream'
                          - 'logs:PutLogEvents'
                      - Effect: Allow
                        Resource:
                          - !Sub 'arn:aws:s3:::${BuildArtifactsBucket}/*'
                        Action: 
                          - 's3:GetObject'
                          - 's3:GetObjectVersion'
                          - 's3:PutObject'

    CodeBuildProject:
        Type: AWS::CodeBuild::Project
        Properties:
            Name: !Sub 'CreateThumbnail_build'
            Description: Build project for the Lambda service
            Artifacts:
                Type: NO_ARTIFACTS
            Environment: 
                Type: LINUX_CONTAINER
                ComputeType: BUILD_GENERAL1_SMALL
                Image: aws/codebuild/nodejs:4.3.2
                EnvironmentVariables:
                    - Name: BUILD_OUTPUT_BUCKET
                      Value: !Ref BuildArtifactsBucket
            ServiceRole: !GetAtt CodeBuildServiceRole.Arn
            Source: 
                Type: GITHUB
                Location: https://github.com/asterkin/lambda-dev.git
                BuildSpec: "version: 0.1\nphases:\n  install:\n    commands:\n     apt-get update && apt-get install -y jq\n  build:\n    commands:\n      - cd js/tutorials/s3 && ./build $BUILD_OUTPUT_BUCKET\nartifacts:\n  files:\n    js/tutorials/s3/test/resource/*.png"


