AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  FacePictureResized:
    Type: AWS::S3::Bucket

  CreateThumbnail:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: CreateThumbnail.handler
      Runtime: nodejs4.3
      Timeout: 60
      Policies: AWSLambdaExecute
      Events:
          PictureUpload:
              Type: S3
              Properties:
                 Bucket: !Ref FacePicture
                 Events: s3:ObjectCreated:*
      Environment:
        Variables:
          RESIZED_BUCKET: !Ref FacePictureResized

  FacePicture:
    Type: AWS::S3::Bucket


