AWSTemplateFormatVersion: '2010-09-09'
Resources:
  CreateThumbnail:
    Properties:
      CodeUri: s3://lambda-dev-tutorials/69ac3a13414a665d37ecf282d1c05d07
      Environment:
        Variables:
          RESIZED_BUCKET:
            Ref: FacePictureResized
      Events:
        PictureUpload:
          Properties:
            Bucket:
              Ref: FacePicture
            Events: s3:ObjectCreated:*
          Type: S3
      Handler: index.handler
      Policies: AWSLambdaExecute
      Runtime: nodejs4.3
      Timeout: 60
    Type: AWS::Serverless::Function
  FacePicture:
    Type: AWS::S3::Bucket
  FacePictureResized:
    Type: AWS::S3::Bucket
Transform: AWS::Serverless-2016-10-31
